apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-root
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: https://github.com/d-cryptic/argo-practice.git
        revision: master
        files:
          - path: applicationsets/**/**/config.json
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
    spec:
      destination:
        namespace: "{{namespace}}"
        server: https://kubernetes.default.svc
      project: "{{project}}"
      source:
        path: "{{path}}"
        repoURL: https://github.com/d-cryptic/argo-practice.git
        targetRevision: HEAD
        directory:
          exclude: "{config.json}"
          include: "*.yaml"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - Validate=true
        automated:
          prune: false
          selfHeal: false
