apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers: resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@tree.mn:barun.d/argocd-nht-assignment.git
    targetRevision: HEAD
    path: envs
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
