apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-deployment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/d-cryptic/argo-practice.git
    targetRevision: HEAD
    path: overlays/production
  destination:
    name: gke_prometheus-396605_us-central1-c_cluster-2
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
