apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/wordpress/wordpress.yaml
  - deployments/wordpress/wordpress-service.yaml
  - deployments/wordpress/redis.yaml
  - deployments/wordpress/redis-service.yaml
  - deployments/wordpress/mysql.yaml
  - deployments/wordpress/mysql-service.yaml
  - hooks/failedsync.yaml
  - hooks/postsync.yaml
  - hooks/presync.yaml
  - hooks/sync.yaml
