apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/wordpress.yaml
  - deployments/wordpress-service.yaml
  - deployments/redis.yaml
  - deployments/redis-service.yaml
  - deployments/mysql.yaml
  - deployments/mysql-service.yaml
  - hooks/failedsync.yaml
  - hooks/postsync.yaml
  - hooks/presync.yaml
  - hooks/sync.yaml
